// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nrpc.proto

package com.sogou.nlu.rpc;

public final class NRpc {
  private NRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NrpcMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sogou.nlu.rpc.NrpcMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
     */
    com.sogou.nlu.rpc.NRpc.NrpcRequestMeta getRequest();
    /**
     * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
     */
    com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
     */
    com.sogou.nlu.rpc.NRpc.NrpcResponseMeta getResponse();
    /**
     * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
     */
    com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder getResponseOrBuilder();

    /**
     * <code>optional int64 correlation_id = 3;</code>
     */
    boolean hasCorrelationId();
    /**
     * <code>optional int64 correlation_id = 3;</code>
     */
    long getCorrelationId();
  }
  /**
   * Protobuf type {@code sogou.nlu.rpc.NrpcMeta}
   */
  public  static final class NrpcMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sogou.nlu.rpc.NrpcMeta)
      NrpcMetaOrBuilder {
    // Use NrpcMeta.newBuilder() to construct.
    private NrpcMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NrpcMeta() {
      correlationId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NrpcMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              correlationId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sogou.nlu.rpc.NRpc.NrpcMeta.class, com.sogou.nlu.rpc.NRpc.NrpcMeta.Builder.class);
    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.sogou.nlu.rpc.NRpc.NrpcRequestMeta request_;
    /**
     * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
     */
    public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta getRequest() {
      return request_ == null ? com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
     */
    public com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder getRequestOrBuilder() {
      return request_ == null ? com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance() : request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.sogou.nlu.rpc.NRpc.NrpcResponseMeta response_;
    /**
     * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
     */
    public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta getResponse() {
      return response_ == null ? com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
     */
    public com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder getResponseOrBuilder() {
      return response_ == null ? com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance() : response_;
    }

    public static final int CORRELATION_ID_FIELD_NUMBER = 3;
    private long correlationId_;
    /**
     * <code>optional int64 correlation_id = 3;</code>
     */
    public boolean hasCorrelationId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 correlation_id = 3;</code>
     */
    public long getCorrelationId() {
      return correlationId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getResponse());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, correlationId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, correlationId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sogou.nlu.rpc.NRpc.NrpcMeta)) {
        return super.equals(obj);
      }
      com.sogou.nlu.rpc.NRpc.NrpcMeta other = (com.sogou.nlu.rpc.NRpc.NrpcMeta) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && (hasCorrelationId() == other.hasCorrelationId());
      if (hasCorrelationId()) {
        result = result && (getCorrelationId()
            == other.getCorrelationId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (hasCorrelationId()) {
        hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCorrelationId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sogou.nlu.rpc.NRpc.NrpcMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sogou.nlu.rpc.NrpcMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sogou.nlu.rpc.NrpcMeta)
        com.sogou.nlu.rpc.NRpc.NrpcMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sogou.nlu.rpc.NRpc.NrpcMeta.class, com.sogou.nlu.rpc.NRpc.NrpcMeta.Builder.class);
      }

      // Construct using com.sogou.nlu.rpc.NRpc.NrpcMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        correlationId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcMeta_descriptor;
      }

      public com.sogou.nlu.rpc.NRpc.NrpcMeta getDefaultInstanceForType() {
        return com.sogou.nlu.rpc.NRpc.NrpcMeta.getDefaultInstance();
      }

      public com.sogou.nlu.rpc.NRpc.NrpcMeta build() {
        com.sogou.nlu.rpc.NRpc.NrpcMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sogou.nlu.rpc.NRpc.NrpcMeta buildPartial() {
        com.sogou.nlu.rpc.NRpc.NrpcMeta result = new com.sogou.nlu.rpc.NRpc.NrpcMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.correlationId_ = correlationId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sogou.nlu.rpc.NRpc.NrpcMeta) {
          return mergeFrom((com.sogou.nlu.rpc.NRpc.NrpcMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sogou.nlu.rpc.NRpc.NrpcMeta other) {
        if (other == com.sogou.nlu.rpc.NRpc.NrpcMeta.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasCorrelationId()) {
          setCorrelationId(other.getCorrelationId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sogou.nlu.rpc.NRpc.NrpcMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sogou.nlu.rpc.NRpc.NrpcMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.sogou.nlu.rpc.NRpc.NrpcRequestMeta request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sogou.nlu.rpc.NRpc.NrpcRequestMeta, com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder, com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder> requestBuilder_;
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public Builder setRequest(com.sogou.nlu.rpc.NRpc.NrpcRequestMeta value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public Builder setRequest(
          com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public Builder mergeRequest(com.sogou.nlu.rpc.NRpc.NrpcRequestMeta value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != null &&
              request_ != com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance()) {
            request_ =
              com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      public com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcRequestMeta request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sogou.nlu.rpc.NRpc.NrpcRequestMeta, com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder, com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sogou.nlu.rpc.NRpc.NrpcRequestMeta, com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder, com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private com.sogou.nlu.rpc.NRpc.NrpcResponseMeta response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sogou.nlu.rpc.NRpc.NrpcResponseMeta, com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder, com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder> responseBuilder_;
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public Builder setResponse(com.sogou.nlu.rpc.NRpc.NrpcResponseMeta value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public Builder setResponse(
          com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public Builder mergeResponse(com.sogou.nlu.rpc.NRpc.NrpcResponseMeta value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              response_ != null &&
              response_ != com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance()) {
            response_ =
              com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      public com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .sogou.nlu.rpc.NrpcResponseMeta response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sogou.nlu.rpc.NRpc.NrpcResponseMeta, com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder, com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sogou.nlu.rpc.NRpc.NrpcResponseMeta, com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder, com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private long correlationId_ ;
      /**
       * <code>optional int64 correlation_id = 3;</code>
       */
      public boolean hasCorrelationId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 correlation_id = 3;</code>
       */
      public long getCorrelationId() {
        return correlationId_;
      }
      /**
       * <code>optional int64 correlation_id = 3;</code>
       */
      public Builder setCorrelationId(long value) {
        bitField0_ |= 0x00000004;
        correlationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 correlation_id = 3;</code>
       */
      public Builder clearCorrelationId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        correlationId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sogou.nlu.rpc.NrpcMeta)
    }

    // @@protoc_insertion_point(class_scope:sogou.nlu.rpc.NrpcMeta)
    private static final com.sogou.nlu.rpc.NRpc.NrpcMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sogou.nlu.rpc.NRpc.NrpcMeta();
    }

    public static com.sogou.nlu.rpc.NRpc.NrpcMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NrpcMeta>
        PARSER = new com.google.protobuf.AbstractParser<NrpcMeta>() {
      public NrpcMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NrpcMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NrpcMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NrpcMeta> getParserForType() {
      return PARSER;
    }

    public com.sogou.nlu.rpc.NRpc.NrpcMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NrpcRequestMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sogou.nlu.rpc.NrpcRequestMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string service_name = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>required string service_name = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>required string service_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>required string method_name = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string method_name = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string method_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional bytes request_body = 3;</code>
     */
    boolean hasRequestBody();
    /**
     * <code>optional bytes request_body = 3;</code>
     */
    com.google.protobuf.ByteString getRequestBody();

    /**
     * <code>optional int64 log_id = 4;</code>
     */
    boolean hasLogId();
    /**
     * <code>optional int64 log_id = 4;</code>
     */
    long getLogId();

    /**
     * <code>optional int64 trace_id = 5;</code>
     */
    boolean hasTraceId();
    /**
     * <code>optional int64 trace_id = 5;</code>
     */
    long getTraceId();

    /**
     * <code>optional int64 span_id = 6;</code>
     */
    boolean hasSpanId();
    /**
     * <code>optional int64 span_id = 6;</code>
     */
    long getSpanId();

    /**
     * <code>optional int64 parent_span_id = 7;</code>
     */
    boolean hasParentSpanId();
    /**
     * <code>optional int64 parent_span_id = 7;</code>
     */
    long getParentSpanId();
  }
  /**
   * Protobuf type {@code sogou.nlu.rpc.NrpcRequestMeta}
   */
  public  static final class NrpcRequestMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sogou.nlu.rpc.NrpcRequestMeta)
      NrpcRequestMetaOrBuilder {
    // Use NrpcRequestMeta.newBuilder() to construct.
    private NrpcRequestMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NrpcRequestMeta() {
      serviceName_ = "";
      methodName_ = "";
      requestBody_ = com.google.protobuf.ByteString.EMPTY;
      logId_ = 0L;
      traceId_ = 0L;
      spanId_ = 0L;
      parentSpanId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NrpcRequestMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serviceName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              methodName_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestBody_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              logId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              traceId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              spanId_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              parentSpanId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcRequestMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcRequestMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.class, com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder.class);
    }

    private int bitField0_;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>required string service_name = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <code>required string method_name = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string method_name = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString requestBody_;
    /**
     * <code>optional bytes request_body = 3;</code>
     */
    public boolean hasRequestBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes request_body = 3;</code>
     */
    public com.google.protobuf.ByteString getRequestBody() {
      return requestBody_;
    }

    public static final int LOG_ID_FIELD_NUMBER = 4;
    private long logId_;
    /**
     * <code>optional int64 log_id = 4;</code>
     */
    public boolean hasLogId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 log_id = 4;</code>
     */
    public long getLogId() {
      return logId_;
    }

    public static final int TRACE_ID_FIELD_NUMBER = 5;
    private long traceId_;
    /**
     * <code>optional int64 trace_id = 5;</code>
     */
    public boolean hasTraceId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 trace_id = 5;</code>
     */
    public long getTraceId() {
      return traceId_;
    }

    public static final int SPAN_ID_FIELD_NUMBER = 6;
    private long spanId_;
    /**
     * <code>optional int64 span_id = 6;</code>
     */
    public boolean hasSpanId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 span_id = 6;</code>
     */
    public long getSpanId() {
      return spanId_;
    }

    public static final int PARENT_SPAN_ID_FIELD_NUMBER = 7;
    private long parentSpanId_;
    /**
     * <code>optional int64 parent_span_id = 7;</code>
     */
    public boolean hasParentSpanId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 parent_span_id = 7;</code>
     */
    public long getParentSpanId() {
      return parentSpanId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, requestBody_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, logId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, traceId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, spanId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, parentSpanId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, requestBody_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, logId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, traceId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, spanId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, parentSpanId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sogou.nlu.rpc.NRpc.NrpcRequestMeta)) {
        return super.equals(obj);
      }
      com.sogou.nlu.rpc.NRpc.NrpcRequestMeta other = (com.sogou.nlu.rpc.NRpc.NrpcRequestMeta) obj;

      boolean result = true;
      result = result && (hasServiceName() == other.hasServiceName());
      if (hasServiceName()) {
        result = result && getServiceName()
            .equals(other.getServiceName());
      }
      result = result && (hasMethodName() == other.hasMethodName());
      if (hasMethodName()) {
        result = result && getMethodName()
            .equals(other.getMethodName());
      }
      result = result && (hasRequestBody() == other.hasRequestBody());
      if (hasRequestBody()) {
        result = result && getRequestBody()
            .equals(other.getRequestBody());
      }
      result = result && (hasLogId() == other.hasLogId());
      if (hasLogId()) {
        result = result && (getLogId()
            == other.getLogId());
      }
      result = result && (hasTraceId() == other.hasTraceId());
      if (hasTraceId()) {
        result = result && (getTraceId()
            == other.getTraceId());
      }
      result = result && (hasSpanId() == other.hasSpanId());
      if (hasSpanId()) {
        result = result && (getSpanId()
            == other.getSpanId());
      }
      result = result && (hasParentSpanId() == other.hasParentSpanId());
      if (hasParentSpanId()) {
        result = result && (getParentSpanId()
            == other.getParentSpanId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServiceName()) {
        hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getServiceName().hashCode();
      }
      if (hasMethodName()) {
        hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getMethodName().hashCode();
      }
      if (hasRequestBody()) {
        hash = (37 * hash) + REQUEST_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getRequestBody().hashCode();
      }
      if (hasLogId()) {
        hash = (37 * hash) + LOG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLogId());
      }
      if (hasTraceId()) {
        hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTraceId());
      }
      if (hasSpanId()) {
        hash = (37 * hash) + SPAN_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSpanId());
      }
      if (hasParentSpanId()) {
        hash = (37 * hash) + PARENT_SPAN_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getParentSpanId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sogou.nlu.rpc.NRpc.NrpcRequestMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sogou.nlu.rpc.NrpcRequestMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sogou.nlu.rpc.NrpcRequestMeta)
        com.sogou.nlu.rpc.NRpc.NrpcRequestMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcRequestMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcRequestMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.class, com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.Builder.class);
      }

      // Construct using com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        logId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        traceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        spanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        parentSpanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcRequestMeta_descriptor;
      }

      public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta getDefaultInstanceForType() {
        return com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance();
      }

      public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta build() {
        com.sogou.nlu.rpc.NRpc.NrpcRequestMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta buildPartial() {
        com.sogou.nlu.rpc.NRpc.NrpcRequestMeta result = new com.sogou.nlu.rpc.NRpc.NrpcRequestMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestBody_ = requestBody_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.logId_ = logId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.traceId_ = traceId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.spanId_ = spanId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.parentSpanId_ = parentSpanId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sogou.nlu.rpc.NRpc.NrpcRequestMeta) {
          return mergeFrom((com.sogou.nlu.rpc.NRpc.NrpcRequestMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sogou.nlu.rpc.NRpc.NrpcRequestMeta other) {
        if (other == com.sogou.nlu.rpc.NRpc.NrpcRequestMeta.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasRequestBody()) {
          setRequestBody(other.getRequestBody());
        }
        if (other.hasLogId()) {
          setLogId(other.getLogId());
        }
        if (other.hasTraceId()) {
          setTraceId(other.getTraceId());
        }
        if (other.hasSpanId()) {
          setSpanId(other.getSpanId());
        }
        if (other.hasParentSpanId()) {
          setParentSpanId(other.getParentSpanId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceName()) {
          return false;
        }
        if (!hasMethodName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sogou.nlu.rpc.NRpc.NrpcRequestMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sogou.nlu.rpc.NRpc.NrpcRequestMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceName_ = "";
      /**
       * <code>required string service_name = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>required string method_name = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            methodName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes request_body = 3;</code>
       */
      public boolean hasRequestBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes request_body = 3;</code>
       */
      public com.google.protobuf.ByteString getRequestBody() {
        return requestBody_;
      }
      /**
       * <code>optional bytes request_body = 3;</code>
       */
      public Builder setRequestBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes request_body = 3;</code>
       */
      public Builder clearRequestBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestBody_ = getDefaultInstance().getRequestBody();
        onChanged();
        return this;
      }

      private long logId_ ;
      /**
       * <code>optional int64 log_id = 4;</code>
       */
      public boolean hasLogId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 log_id = 4;</code>
       */
      public long getLogId() {
        return logId_;
      }
      /**
       * <code>optional int64 log_id = 4;</code>
       */
      public Builder setLogId(long value) {
        bitField0_ |= 0x00000008;
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 log_id = 4;</code>
       */
      public Builder clearLogId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        logId_ = 0L;
        onChanged();
        return this;
      }

      private long traceId_ ;
      /**
       * <code>optional int64 trace_id = 5;</code>
       */
      public boolean hasTraceId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 trace_id = 5;</code>
       */
      public long getTraceId() {
        return traceId_;
      }
      /**
       * <code>optional int64 trace_id = 5;</code>
       */
      public Builder setTraceId(long value) {
        bitField0_ |= 0x00000010;
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 trace_id = 5;</code>
       */
      public Builder clearTraceId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        traceId_ = 0L;
        onChanged();
        return this;
      }

      private long spanId_ ;
      /**
       * <code>optional int64 span_id = 6;</code>
       */
      public boolean hasSpanId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 span_id = 6;</code>
       */
      public long getSpanId() {
        return spanId_;
      }
      /**
       * <code>optional int64 span_id = 6;</code>
       */
      public Builder setSpanId(long value) {
        bitField0_ |= 0x00000020;
        spanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 span_id = 6;</code>
       */
      public Builder clearSpanId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        spanId_ = 0L;
        onChanged();
        return this;
      }

      private long parentSpanId_ ;
      /**
       * <code>optional int64 parent_span_id = 7;</code>
       */
      public boolean hasParentSpanId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 parent_span_id = 7;</code>
       */
      public long getParentSpanId() {
        return parentSpanId_;
      }
      /**
       * <code>optional int64 parent_span_id = 7;</code>
       */
      public Builder setParentSpanId(long value) {
        bitField0_ |= 0x00000040;
        parentSpanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 parent_span_id = 7;</code>
       */
      public Builder clearParentSpanId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        parentSpanId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sogou.nlu.rpc.NrpcRequestMeta)
    }

    // @@protoc_insertion_point(class_scope:sogou.nlu.rpc.NrpcRequestMeta)
    private static final com.sogou.nlu.rpc.NRpc.NrpcRequestMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sogou.nlu.rpc.NRpc.NrpcRequestMeta();
    }

    public static com.sogou.nlu.rpc.NRpc.NrpcRequestMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NrpcRequestMeta>
        PARSER = new com.google.protobuf.AbstractParser<NrpcRequestMeta>() {
      public NrpcRequestMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NrpcRequestMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NrpcRequestMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NrpcRequestMeta> getParserForType() {
      return PARSER;
    }

    public com.sogou.nlu.rpc.NRpc.NrpcRequestMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NrpcResponseMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sogou.nlu.rpc.NrpcResponseMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 error_code = 1;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 error_code = 1;</code>
     */
    int getErrorCode();

    /**
     * <code>optional string error_text = 2;</code>
     */
    boolean hasErrorText();
    /**
     * <code>optional string error_text = 2;</code>
     */
    java.lang.String getErrorText();
    /**
     * <code>optional string error_text = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorTextBytes();

    /**
     * <code>optional bytes response_body = 3;</code>
     */
    boolean hasResponseBody();
    /**
     * <code>optional bytes response_body = 3;</code>
     */
    com.google.protobuf.ByteString getResponseBody();
  }
  /**
   * Protobuf type {@code sogou.nlu.rpc.NrpcResponseMeta}
   */
  public  static final class NrpcResponseMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sogou.nlu.rpc.NrpcResponseMeta)
      NrpcResponseMetaOrBuilder {
    // Use NrpcResponseMeta.newBuilder() to construct.
    private NrpcResponseMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NrpcResponseMeta() {
      errorCode_ = 0;
      errorText_ = "";
      responseBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NrpcResponseMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorText_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              responseBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcResponseMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcResponseMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.class, com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder.class);
    }

    private int bitField0_;
    public static final int ERROR_CODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>optional int32 error_code = 1;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 error_code = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERROR_TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorText_;
    /**
     * <code>optional string error_text = 2;</code>
     */
    public boolean hasErrorText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string error_text = 2;</code>
     */
    public java.lang.String getErrorText() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorTextBytes() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSE_BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString responseBody_;
    /**
     * <code>optional bytes response_body = 3;</code>
     */
    public boolean hasResponseBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes response_body = 3;</code>
     */
    public com.google.protobuf.ByteString getResponseBody() {
      return responseBody_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorText_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, responseBody_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorText_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, responseBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sogou.nlu.rpc.NRpc.NrpcResponseMeta)) {
        return super.equals(obj);
      }
      com.sogou.nlu.rpc.NRpc.NrpcResponseMeta other = (com.sogou.nlu.rpc.NRpc.NrpcResponseMeta) obj;

      boolean result = true;
      result = result && (hasErrorCode() == other.hasErrorCode());
      if (hasErrorCode()) {
        result = result && (getErrorCode()
            == other.getErrorCode());
      }
      result = result && (hasErrorText() == other.hasErrorText());
      if (hasErrorText()) {
        result = result && getErrorText()
            .equals(other.getErrorText());
      }
      result = result && (hasResponseBody() == other.hasResponseBody());
      if (hasResponseBody()) {
        result = result && getResponseBody()
            .equals(other.getResponseBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrorCode()) {
        hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode();
      }
      if (hasErrorText()) {
        hash = (37 * hash) + ERROR_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getErrorText().hashCode();
      }
      if (hasResponseBody()) {
        hash = (37 * hash) + RESPONSE_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getResponseBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sogou.nlu.rpc.NRpc.NrpcResponseMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sogou.nlu.rpc.NrpcResponseMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sogou.nlu.rpc.NrpcResponseMeta)
        com.sogou.nlu.rpc.NRpc.NrpcResponseMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcResponseMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcResponseMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.class, com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.Builder.class);
      }

      // Construct using com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        responseBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sogou.nlu.rpc.NRpc.internal_static_sogou_nlu_rpc_NrpcResponseMeta_descriptor;
      }

      public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta getDefaultInstanceForType() {
        return com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance();
      }

      public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta build() {
        com.sogou.nlu.rpc.NRpc.NrpcResponseMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta buildPartial() {
        com.sogou.nlu.rpc.NRpc.NrpcResponseMeta result = new com.sogou.nlu.rpc.NRpc.NrpcResponseMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorText_ = errorText_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.responseBody_ = responseBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sogou.nlu.rpc.NRpc.NrpcResponseMeta) {
          return mergeFrom((com.sogou.nlu.rpc.NRpc.NrpcResponseMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sogou.nlu.rpc.NRpc.NrpcResponseMeta other) {
        if (other == com.sogou.nlu.rpc.NRpc.NrpcResponseMeta.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorText()) {
          bitField0_ |= 0x00000002;
          errorText_ = other.errorText_;
          onChanged();
        }
        if (other.hasResponseBody()) {
          setResponseBody(other.getResponseBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sogou.nlu.rpc.NRpc.NrpcResponseMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sogou.nlu.rpc.NRpc.NrpcResponseMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorCode_ ;
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorText_ = "";
      /**
       * <code>optional string error_text = 2;</code>
       */
      public boolean hasErrorText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public java.lang.String getErrorText() {
        java.lang.Object ref = errorText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorTextBytes() {
        java.lang.Object ref = errorText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public Builder setErrorText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public Builder clearErrorText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorText_ = getDefaultInstance().getErrorText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public Builder setErrorTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorText_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString responseBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response_body = 3;</code>
       */
      public boolean hasResponseBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes response_body = 3;</code>
       */
      public com.google.protobuf.ByteString getResponseBody() {
        return responseBody_;
      }
      /**
       * <code>optional bytes response_body = 3;</code>
       */
      public Builder setResponseBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        responseBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response_body = 3;</code>
       */
      public Builder clearResponseBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        responseBody_ = getDefaultInstance().getResponseBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sogou.nlu.rpc.NrpcResponseMeta)
    }

    // @@protoc_insertion_point(class_scope:sogou.nlu.rpc.NrpcResponseMeta)
    private static final com.sogou.nlu.rpc.NRpc.NrpcResponseMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sogou.nlu.rpc.NRpc.NrpcResponseMeta();
    }

    public static com.sogou.nlu.rpc.NRpc.NrpcResponseMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NrpcResponseMeta>
        PARSER = new com.google.protobuf.AbstractParser<NrpcResponseMeta>() {
      public NrpcResponseMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NrpcResponseMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NrpcResponseMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NrpcResponseMeta> getParserForType() {
      return PARSER;
    }

    public com.sogou.nlu.rpc.NRpc.NrpcResponseMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sogou_nlu_rpc_NrpcMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sogou_nlu_rpc_NrpcMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sogou_nlu_rpc_NrpcRequestMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sogou_nlu_rpc_NrpcRequestMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sogou_nlu_rpc_NrpcResponseMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sogou_nlu_rpc_NrpcResponseMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnrpc.proto\022\rsogou.nlu.rpc\"\206\001\n\010NrpcMeta" +
      "\022/\n\007request\030\001 \001(\0132\036.sogou.nlu.rpc.NrpcRe" +
      "questMeta\0221\n\010response\030\002 \001(\0132\037.sogou.nlu." +
      "rpc.NrpcResponseMeta\022\026\n\016correlation_id\030\003" +
      " \001(\003\"\235\001\n\017NrpcRequestMeta\022\024\n\014service_name" +
      "\030\001 \002(\t\022\023\n\013method_name\030\002 \002(\t\022\024\n\014request_b" +
      "ody\030\003 \001(\014\022\016\n\006log_id\030\004 \001(\003\022\020\n\010trace_id\030\005 " +
      "\001(\003\022\017\n\007span_id\030\006 \001(\003\022\026\n\016parent_span_id\030\007" +
      " \001(\003\"Q\n\020NrpcResponseMeta\022\022\n\nerror_code\030\001" +
      " \001(\005\022\022\n\nerror_text\030\002 \001(\t\022\025\n\rresponse_bod",
      "y\030\003 \001(\014B\"\n\021com.sogou.nlu.rpcB\004NRpc\200\001\001\210\001\001" +
      "\220\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sogou_nlu_rpc_NrpcMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sogou_nlu_rpc_NrpcMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sogou_nlu_rpc_NrpcMeta_descriptor,
        new java.lang.String[] { "Request", "Response", "CorrelationId", });
    internal_static_sogou_nlu_rpc_NrpcRequestMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sogou_nlu_rpc_NrpcRequestMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sogou_nlu_rpc_NrpcRequestMeta_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "RequestBody", "LogId", "TraceId", "SpanId", "ParentSpanId", });
    internal_static_sogou_nlu_rpc_NrpcResponseMeta_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sogou_nlu_rpc_NrpcResponseMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sogou_nlu_rpc_NrpcResponseMeta_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorText", "ResponseBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
